# Site settings
title: Belle Photographie
email: wyman.lucy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: ''
#url: 
twitter_username: 
github_username: lucywyman
source: .
destination: ./site
layouts: ./layouts
data_source: ./data

permalink: /:title.html
paginate: 20

# Build settings
markdown: kramdown

